blank_issues_enabled: false
contact_links:
  - name: ğŸ¤– å¸¸è§é—®é¢˜
    url: https://uni-echarts.xiaohe.ink/guide/faq
    about: æ”¶å½•é«˜é¢‘é—®é¢˜åŠå¯¹åº”çš„è§£å†³æ–¹æ¡ˆï¼Œå¸®åŠ©ä½ å¿«é€Ÿå®šä½å’Œè§£å†³é—®é¢˜ã€‚
  - name: ğŸ“‹ å·²è§£ç­”é—®é¢˜
    url: https://github.com/xiaohe0601/uni-echarts/issues?q=is%3Aissue%20label%3A%22%F0%9F%98%80%20answer%22
    about: æŸ¥çœ‹ç¤¾åŒºå·²è§£ç­”çš„é—®é¢˜ï¼Œè·å–å®ç”¨å‚è€ƒå’ŒæŠ€å·§ã€‚
  - name: ğŸ’¬ è®¨è®ºåŒº
    url: https://github.com/xiaohe0601/uni-echarts/discussions
    about: æ¬¢è¿åœ¨è®¨è®ºåŒºä¸æˆ‘ä»¬äº’åŠ¨ï¼Œåˆ†äº«ç»éªŒå’Œå»ºè®®ã€‚